/**
 * Shape of a curated, vendored design preset. The catalog that consumes it is
 * generated by `scripts/generate-theme-presets.mjs` from
 * `https://ui.shadcn.com/init?preset=<code>`, so the app never talks to the
 * network at runtime.
 */
export type PresetConfig = {
  style: string
  baseColor: string
  theme: string
  chartColor: string
  iconLibrary: string
  font: string
  fontHeading: string
  radius: string
  menuAccent: string
  menuColor: string
}

export type ThemePreset = {
  /** Preset code understood by ui.shadcn.com and `shadcn/preset`. */
  code: string
  name: string
  description: string
  config: PresetConfig
  /** CSS custom properties for the light theme, including `radius`. */
  light: Record<string, string>
  /** CSS custom properties for the dark theme. */
  dark: Record<string, string>
}
