/**
 * Datos de muestra de Proyectos. Se cargan una vez en el store del layout
 * de `/projects`, así la grilla y la pantalla de edición comparten las filas.
 */

import { type Project } from "./project-types"

export const PROJECTS: Project[] = [
  {
    id: "p-1",
    name: "Rediseño del portal",
    business: "AgileTeam Corp",
    description: "Nuevo design system y home pública",
    status: "active",
    priority: "medium",
    startDate: "2026-08-03",
    endDate: "2026-11-27",
    team: ["Juan Pérez", "María García", "Carlos López"],
    color: "#2563eb",
    tasks: [
      {
        id: "t-1",
        title: "Auditoría de componentes",
        description: "Inventario de los componentes actuales y sus variantes",
        status: "done",
        priority: "medium",
        assignee: "María García",
        startDate: "2026-08-03",
        endDate: "2026-08-21",
        estimatedHours: 24,
        tags: ["ux", "auditoría"],
      },
      {
        id: "t-2",
        title: "Tokens de diseño",
        description: "Color, tipografía, espaciado y radios",
        status: "done",
        priority: "high",
        assignee: "Juan Pérez",
        startDate: "2026-08-17",
        endDate: "2026-09-11",
        estimatedHours: 32,
        tags: ["design-system"],
      },
      {
        id: "t-3",
        title: "Nueva home",
        description: "Implementación de la home con el sistema nuevo",
        status: "done",
        priority: "high",
        assignee: "Carlos López",
        startDate: "2026-09-14",
        endDate: "2026-10-09",
        estimatedHours: 40,
        tags: ["frontend"],
      },
      {
        id: "t-4",
        title: "Página de precios",
        description: "Comparativa de planes y preguntas frecuentes",
        status: "in_progress",
        priority: "medium",
        assignee: "María García",
        startDate: "2026-10-05",
        endDate: "2026-10-30",
        estimatedHours: 20,
        tags: ["frontend", "contenido"],
      },
      {
        id: "t-5",
        title: "Migración de legales",
        description: "Portar las páginas de términos y privacidad",
        status: "todo",
        priority: "low",
        assignee: "",
        startDate: "2026-11-02",
        endDate: "2026-11-27",
        estimatedHours: 8,
        tags: ["contenido"],
      },
    ],
  },
  {
    id: "p-2",
    name: "Migración a la nube",
    business: "NovaSoft",
    description: "Mover los servicios a contenedores",
    status: "active",
    priority: "high",
    startDate: "2026-07-01",
    endDate: "2026-10-30",
    team: ["Ana Suárez", "Pablo Ríos"],
    color: "#7c3aed",
    tasks: [
      {
        id: "t-6",
        title: "Relevamiento de servicios",
        description: "Dependencias, tráfico y ventanas de mantenimiento",
        status: "done",
        priority: "high",
        assignee: "Ana Suárez",
        startDate: "2026-07-01",
        endDate: "2026-07-24",
        estimatedHours: 30,
        tags: ["infra"],
      },
      {
        id: "t-7",
        title: "Imágenes Docker",
        description: "Empaquetado reproducible de cada servicio",
        status: "in_progress",
        priority: "high",
        assignee: "Pablo Ríos",
        startDate: "2026-07-27",
        endDate: "2026-09-04",
        estimatedHours: 45,
        tags: ["infra", "ci"],
      },
      {
        id: "t-8",
        title: "Pipeline de despliegue",
        description: "Integración continua y promoción entre entornos",
        status: "in_progress",
        priority: "medium",
        assignee: "Ana Suárez",
        startDate: "2026-09-07",
        endDate: "2026-10-16",
        estimatedHours: 36,
        tags: ["ci"],
      },
      {
        id: "t-9",
        title: "Prueba de carga",
        description: "Validar el rendimiento con el tráfico real",
        status: "todo",
        priority: "medium",
        assignee: "",
        startDate: "2026-10-19",
        endDate: "2026-10-30",
        estimatedHours: 16,
        tags: ["performance"],
      },
    ],
  },
  {
    id: "p-3",
    name: "App móvil de campo",
    business: "TechCorp",
    description: "",
    status: "planning",
    priority: "low",
    startDate: "2026-11-02",
    endDate: "2027-02-26",
    team: ["Sofía Medina"],
    color: "#0ea5e9",
    tasks: [
      {
        id: "t-10",
        title: "Definición del alcance",
        description: "Casos de uso y usuarios piloto",
        status: "in_progress",
        priority: "medium",
        assignee: "Sofía Medina",
        startDate: "2026-10-01",
        endDate: "2026-11-13",
        estimatedHours: 18,
        tags: ["producto"],
      },
      {
        id: "t-11",
        title: "Prototipo navegable",
        description: "Flujo de carga de visitas",
        status: "todo",
        priority: "low",
        assignee: "",
        startDate: "2026-11-16",
        endDate: "2026-12-18",
        estimatedHours: 24,
        tags: ["ux"],
      },
    ],
  },
  {
    id: "p-4",
    name: "Portal de proveedores",
    business: "AgileTeam Corp",
    description: "Altas, órdenes de compra y facturación",
    status: "paused",
    priority: "high",
    startDate: "2026-05-04",
    endDate: "2026-12-18",
    team: [],
    color: "#f59e0b",
    tasks: [
      {
        id: "t-12",
        title: "Alta de proveedores",
        description: "Formulario y validación de documentación",
        status: "done",
        priority: "high",
        assignee: "Carlos López",
        startDate: "2026-05-04",
        endDate: "2026-06-26",
        estimatedHours: 40,
        tags: ["backend"],
      },
      {
        id: "t-13",
        title: "Órdenes de compra",
        description: "Circuito de aprobación por montos",
        status: "done",
        priority: "high",
        assignee: "Lucía Fernández",
        startDate: "2026-06-29",
        endDate: "2026-08-14",
        estimatedHours: 48,
        tags: ["backend", "workflow"],
      },
      {
        id: "t-14",
        title: "Facturación",
        description: "Integración con el organismo fiscal",
        status: "todo",
        priority: "high",
        assignee: "",
        startDate: "2026-10-19",
        endDate: "2026-12-18",
        estimatedHours: 60,
        tags: ["backend", "integraciones"],
      },
    ],
  },
  {
    id: "p-5",
    name: "Observabilidad",
    business: "NovaSoft",
    description: "Métricas, trazas y alertas",
    status: "completed",
    priority: "medium",
    startDate: "2026-03-02",
    endDate: "2026-06-30",
    team: ["Juan Pérez", "Lucía Fernández"],
    color: "#10b981",
    tasks: [
      {
        id: "t-15",
        title: "Métricas de aplicación",
        description: "Instrumentar los servicios principales",
        status: "done",
        priority: "medium",
        assignee: "Juan Pérez",
        startDate: "2026-03-02",
        endDate: "2026-04-10",
        estimatedHours: 32,
        tags: ["observabilidad"],
      },
      {
        id: "t-16",
        title: "Trazas distribuidas",
        description: "Correlación entre servicios",
        status: "done",
        priority: "medium",
        assignee: "Lucía Fernández",
        startDate: "2026-04-13",
        endDate: "2026-05-22",
        estimatedHours: 36,
        tags: ["observabilidad"],
      },
      {
        id: "t-17",
        title: "Tableros y alertas",
        description: "Paneles por servicio y umbrales de aviso",
        status: "done",
        priority: "high",
        assignee: "Juan Pérez",
        startDate: "2026-05-25",
        endDate: "2026-06-30",
        estimatedHours: 28,
        tags: ["observabilidad", "sre"],
      },
    ],
  },
  {
    id: "p-6",
    name: "Facturación electrónica",
    business: "TechCorp",
    description: "Emisión y consulta de comprobantes",
    status: "planning",
    priority: "high",
    startDate: "2026-09-01",
    endDate: "2027-01-29",
    team: ["Carlos López", "María García"],
    color: "#ef4444",
    tasks: [
      {
        id: "t-18",
        title: "Certificados y credenciales",
        description: "Alta en el organismo fiscal y pruebas en homologación",
        status: "done",
        priority: "high",
        assignee: "Carlos López",
        startDate: "2026-09-01",
        endDate: "2026-09-25",
        estimatedHours: 20,
        tags: ["integraciones"],
      },
      {
        id: "t-19",
        title: "Emisión de comprobantes",
        description: "Generación, firma y envío",
        status: "in_progress",
        priority: "high",
        assignee: "Carlos López",
        startDate: "2026-09-28",
        endDate: "2026-11-20",
        estimatedHours: 52,
        tags: ["backend"],
      },
      {
        id: "t-20",
        title: "Pantalla de consulta",
        description: "Búsqueda y descarga de comprobantes",
        status: "todo",
        priority: "medium",
        assignee: "María García",
        startDate: "2026-11-23",
        endDate: "2026-12-31",
        estimatedHours: 30,
        tags: ["frontend"],
      },
    ],
  },
]
